### ISSUE TITLE
question: make install, operator.yaml

### ISSUE THREAD

**Issue by ct-clmsn** [sylabs/slurm-operator#160]
where are the built programs installed system-wide? `make install` isn't supported currently and redbox is stored into $PWD/bin.

operator.yaml (and some of the other yamls) require pulling a container from the sylabs container storage site to run the operator, results, and configurator programs. Could support be provided either as a script - that allows users to build those containers (with sudo or as root) in the build directory (possible makefile command - like 'make operator-container') and have them stored in the system's container cache to avoid pulling the images from a remote container storage solution?

**Comment by sashayakovtseva** [comment]
Hello @ct-clmsn,

There is a single program now - `red-box` - and indeed it is not installed anywhere. This is a subject to change soon, I believe, not sure yet.

About images: there is `make push` command currently that builds, signs and pushes SIFs to sylabs cloud, as a workaround (if you don't want to pull images, btw why?) you can remove push step. That will result in SIF created on your host, but then comes the Singularity-CRI hack part. You will have to put those SIFs into Singularity-CRI's store dir (`/var/lib/singularity` by default) and modify (or create) `registry.json` that will have info about each image that was placed there. 

That should work, but I really wonder why pulling images is a problem. I am not sure whether we want to support this edge case where images are not pulled from cloud... Can explain in details why you and others may need this? Feel free to open feature request in Singularity-CRI repo :)

**Comment by ct-clmsn** [comment]
@sashayakovtseva this is related to [#160](https://github.com/sylabs/slurm-operator/issues/160). I did some digging around the source and didn't see build rules for those programs - I'll give `make push` a shot. Thanks for clarification!

I was thinking some systems may not have access to the global (public internet) sylabs container repository due to corporate network policies. Your explanation is perfect - all someone would need to do is point the `make push` command to the proper container repository and they should be good to go. Thanks again for the prompt response!
